doyto:
  query:
    config:
      dialect: win.doyto.query.dialect.HSQLDBDialect
      map-camel-case-to-underscore: true
      join-table-format: "t_%s_and_%s"

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation: trace
    win.doyto.query.sql.SqlAndArgs: debug
